### ISSUE TITLE
Unfinished tutorial

### ISSUE THREAD

**Issue by Bronzdragon** [BGR360/UE4_CustomAssetTutorial#1]
Hey, back in 2015 you started writing a tutorial (https://wiki.unrealengine.com/Creating_A_Custom_Importable_Asset), which seems never got finished. I assume since it's so long ago, you've lost interested in finishing it. I wanted to ask if you have it somewhere else available though, perchance.

**Comment by BGR360** [comment]
Yeah, sorry :( I don't have it anywhere else. Unfortunately, it's been so long since I've touched Unreal Engine that I don't think I'd be able to finish it today even if I wanted to. I hope you find the help you're looking for!

**Comment by Bronzdragon** [comment]
Turns out, Epic released a tutorial on this exact topic later on the day I initially asked ([Link for future reference](https://academy.unrealengine.com/Class-Viewer/plugins)). Talk about good timing, right? Anyway, thanks for getting back to me.

**Comment by BGR360** [comment]
Wow, that's great timing! Lucky you :)
